[wallpaper]
name = "CineShader Lava"
author = "edankwan"
version = "1.0.0"
source_url = "https://www.shadertoy.com/view/3sySRK"
tags = ["cineshader", "lavalamp"]
passes = ["image"]

[render_targets.image]
source = "image.glsl"
bindings = []

